name: Test Workflow

on:
  push:
    branches: [master]


jobs:
  test_job:
    name: Executando Job Teste
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: 'lgmbx'
        password: ${{secrets.DOCKER_PSA}}
          

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        tags: lgmbx/wf:latest
        push: true

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        -name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: https://registry.hub.docker.com/wf:release
             

          
