name: Test Workflow

on:
  push:
    branches: [master]

env:
  DOCKER_IMAGE_NAME: wf

jobs:
  test_job:
    name: Executando Job Teste
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASS}}
          

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        tags: '${{env.DOCKER_IMAGE_NAME}}:latest'
        push: true

   
             

          
