name: Test Workflow

on:
  push:
    branches: [master]

env:
  DOCKER_IMAGE_NAME: wf
  AZURE_WEB_APP: weatherforecast-teste

jobs:
  test_job:
    name: Executando Job Teste
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASS}}
          

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        tags: '${{secrets.DOCKER_USER}}/${{env.DOCKER_IMAGE_NAME}}:latest'
        push: true

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
   
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v3.0.0
      with:
        # Name of the Azure Web App
        app-name: '${{env.AZURE_WEB_APP}}'
        # Applies to Web App Containers only: Specify the fully qualified container image(s) name. For example, 'myregistry.azurecr.io/nginx:latest' or 'python:3.7.2-alpine/'. For multi-container scenario multiple container image names can be provided (multi-line separated)
        images: '${{secrets.DOCKER_USER}}/${{env.DOCKER_IMAGE_NAME}}:latest'

          

          
