name: Test Workflow

on:
  push:
    branches: [master]


jobs:
  test_job:
    name: Executando Job Teste
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: 'lgmbx'
        password: ${{secrets.DOCKER_PSA}}
          
          
            

          
