name: Test Workflow

on:
  push:
    branches: [master]


jobs:
  test_job:
    name: Executando Job Teste
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Executando comando
      run: echo "alo alo"
          
            

          
